theme: jekyll-theme-minimal
title: IGPenguin's Hmm
description: Your daily dose of soft skills enhancement.
title_image: "https://github.com/IGPenguin/hmm/blob/gh-pages/assets/png/favicon.png?raw=true"
