theme: jekyll-theme-minimal
title: Penguin's Stashboard
description: Inspirational digital space.
title_image: "https://github.com/IntergalacticPenguin/stashboard/blob/gh-pages/assets/png/favicon.png?raw=true"
